const userActionTypes = {
	FETCH_USER_START: 'FETCH_USER_START',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
	USER_SEARCHING: 'USER_SEARCHING'
};

export default userActionTypes;
